DROP DATABASE IF EXISTS escaldeMVC;
CREATE DATABASE escaldeMVC;
USE escaldeMVC;

CREATE TABLE user (
    id TINYINT UNSIGNED AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    creationDate DATE,
    score INT,

    CONSTRAINT UK_username UNIQUE KEY (username),
    CONSTRAINT PK_idUser PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;